#!/usr/bin/env bash
# A Bash script that configures an Ubuntu server
# Requirements:
#+ localhost resolves to 127.0.0.2.
#+ facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts.new

# Resolving localhost to 127.0.0.2.
echo "127.0.0.2		localhost" > ~/hosts.new

# Resolving facebook.com to 8.8.8.8
echo "8.8.8.8		facebook.com" >> ~/hosts.new

# Forcing this command
cp -f ~/hosts.new /etc/hosts
