#!/usr/bin/env bash
# A Bash script that displays numbers from 1 to 100 in a list format.
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is a multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number.
# Debugged with help of ChatGP

for ((num=1; num<=100; num++))
do
	# Check if num is a multiple of 3 and 5
	if ((num % 3 == 0)) && ((num % 5 == 0))
	then
		echo "FizzBuzz"
	
	# Check if num is a multiple of 3
	elif ((num % 3 == 0))
	then
		echo "Fizz"
	
	# Check if num is a multiple of 5
	elif ((num % 5 == 0))
	then
		echo "Buzz"
	
	# Otherwise, dusplay num
	else
		echo $num
	fi
done

