#!/usr/bin/env bash
# This script displays the content of the current directory in list format
# Only displays the part of the name after the first dash

myList=$(ls)

for i in $myList
do
	echo "$i" | cut -d '-' -f2
done
