#!/usr/bin/env bash
# A Bash script that displays the PID, along with the process name, of processes whose name contain the word bash.

for pid in /proc/*/
do
    pid="${pid%/}"
    process_name=$(cat "$pid/cmdline" 2>/dev/null | tr -d '\0' | awk -F "/" '{print $NF}')
    
    if [[ $process_name == *bash* ]]; then
        echo "PID: ${pid##*/}   Process Name: $process_name"
    fi
done

